/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ClasesAplicacion.ListaUsuarios;
import ClasesAplicacion.Partida;
import ClasesAplicacion.Usuario;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class Puntuaciones extends javax.swing.JFrame {

    String dni;
    int contador=0;
    /**
     * Creates new form Puntuaciones
     */
    public Puntuaciones() {
        initComponents();
        ArrayList<Partida> listaPartidas = new ArrayList<>();
        ListaUsuarios.cargarDatos();
        try{
        for (Usuario usuario : ListaUsuarios.getLista().values()) {
            for(Partida partidas : usuario.getListaPartida())
            listaPartidas.add(partidas);
        }
        } catch (NullPointerException npe ){
            JOptionPane.showMessageDialog(this, "No existen ususario registrados");            
        }
        // metodo burbuja
        int intercambios = 0, comparaciones = 0;
        Partida aux = new Partida("","");
        for (int i = 1; i < listaPartidas.size(); i++) {
            for (int j = listaPartidas.size() - 1; j >= i; j--) {
                comparaciones++;
                if (listaPartidas.get(j-1).getPuntuacion() < (listaPartidas.get(j).getPuntuacion() )) {
                    intercambios++;
                    aux = listaPartidas.get(j-1);
                    listaPartidas.set(j-1, listaPartidas.get(j));
                    listaPartidas.set(j, aux);
                }
            }
        }
        DefaultTableModel model = (DefaultTableModel) jTablePuntuaciones.getModel();
        model.setRowCount(listaPartidas.size());
        model.setColumnCount(2);
        jTablePuntuaciones.setModel(model);
        for(Partida partida : listaPartidas){
            jTablePuntuaciones.setValueAt(partida.getPuntuacion(), contador, 1);
            jTablePuntuaciones.setValueAt(partida.getUsuario(), contador, 0);
            contador++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAtras = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePuntuaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jTablePuntuaciones.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTablePuntuaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntuacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePuntuaciones.setGridColor(new java.awt.Color(0, 0, 0));
        jTablePuntuaciones.setOpaque(false);
        jTablePuntuaciones.setSelectionBackground(new java.awt.Color(0, 204, 204));
        jTablePuntuaciones.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTablePuntuaciones.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(jTablePuntuaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtras)
                        .addGap(0, 321, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAtras)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        Menu m = new Menu();
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePuntuaciones;
    // End of variables declaration//GEN-END:variables
}
