/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ClasesAplicacion.Usuario;
import java.util.HashMap;
import ClasesAplicacion.ListaUsuarios;
import ClasesAplicacion.Partida;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author david
 */
public class RegistroPartidas extends javax.swing.JFrame {

    String dni;
    int contador = 1;
    int i = 0;

    /**
     * Creates new form RegistroPartidas
     */
    public RegistroPartidas(String dni) {

        this.dni = dni;
        initComponents();
        ListaUsuarios.cargarDatos();
        HashMap<String, Usuario> lista;
        lista = ListaUsuarios.getLista();
        Usuario u;
        u = lista.get(dni);
        DefaultTableModel model = (DefaultTableModel) jTablePartidas.getModel();
        model.setRowCount(u.getListaPartida().size());
        model.setColumnCount(3);
        jTablePartidas.setModel(model);

        for (Partida partida : u.getListaPartida()) {
            jTablePartidas.setValueAt(contador, i, 0);
            jTablePartidas.setValueAt(partida.getDificultad(), i, 1);
            jTablePartidas.setValueAt(partida.getPuntuacion(), i, 2);
            contador++;
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTablero = new javax.swing.JTable();
        jButtonAtras = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePartidas = new javax.swing.JTable();

        jTableTablero.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTableTablero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTablero.setGridColor(new java.awt.Color(0, 102, 0));
        jTableTablero.setOpaque(false);
        jTableTablero.setSelectionBackground(new java.awt.Color(0, 102, 0));
        jTableTablero.setSelectionForeground(new java.awt.Color(51, 153, 0));
        jTableTablero.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTableTablero);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jTablePartidas.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jTablePartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Partida", "Dificultad", "Puntuacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePartidas.setGridColor(new java.awt.Color(0, 0, 0));
        jTablePartidas.setOpaque(false);
        jTablePartidas.setSelectionBackground(new java.awt.Color(0, 204, 204));
        jTablePartidas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTablePartidas.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(jTablePartidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtras)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAtras))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        OpcionesPartida op = new OpcionesPartida(dni);
        this.setVisible(false);
        op.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePartidas;
    private javax.swing.JTable jTableTablero;
    // End of variables declaration//GEN-END:variables
}
